version: "3"
services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/det:backend
    container_name: "backend"
    ports:
      - "3001:3001"

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/det:frontend
    container_name: "frontend"
    depends_on:
      - backend
    ports:
      - "3000:3000"
