version: '3.4'
services:
  
  backend:
   
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /src
   
    ports:
      - "3001:3001"

  frontend:
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    working_dir: /src
   
    ports:
      - "3000:3000"
  
volumes:
  database-data:
  backend-uploads: