name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker container
        run: docker compose up -d detec2
      - name: Publish image to docker hub
        run: docker push mahbubrahim/detec2:latest
        
  deploy:
    needs: build
    runs-on: [ip-172-31-1-127]
    steps:
      - name: Pull image from docker hub
        run: docker pull detec2/app:latest
      - name: Delete old container
        run: docker rm -f app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name app-container detec2/app
